# Generated by Django 2.1.2 on 2018-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_auto_20181023_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estadoMascota',
            field=models.CharField(default='rescatado', max_length=50),
        ),
    ]
