# Generated by Django 2.1 on 2018-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_mascota_estadomascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default='aaa', max_length=50),
        ),
    ]
