# Generated by Django 2.1.2 on 2018-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_auto_20181024_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='correoPersona',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fechaNac',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='passwd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipoVivienda',
            field=models.TextField(null=True),
        ),
    ]
