# Generated by Django 2.1.2 on 2018-11-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_auto_20181102_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estadoMascota',
            field=models.CharField(default='Rescatado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombreMascota',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
