# Generated by Django 2.1.3 on 2018-11-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_auto_20181102_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/imagesmascotas/'),
        ),
    ]
