# Generated by Django 2.1.3 on 2018-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0011_auto_20181105_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
