# Generated by Django 2.1.2 on 2018-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0012_auto_20181105_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
