# Generated by Django 2.1.2 on 2018-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0013_auto_20181105_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNac',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
