# Generated by Django 2.1.2 on 2018-11-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0014_auto_20181105_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='passwd',
        ),
    ]
